# Generated by Django 3.2 on 2021-05-22 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0002_trxcinetpay_trxcorrespondent_trxdifference_trxfailedcinetpay_trxoperateur_trxrightcorrespodent_trxsu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='Devise',
            new_name='cel_phone_num',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='EtatTransaction',
            new_name='cpm_amount',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='IdPaiment',
            new_name='cpm_currency',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='IdTransaction',
            new_name='cpm_payid',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='SiteId',
            new_name='cpm_payment_date',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='Montant',
            new_name='cpm_site_id',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='Telephone',
            new_name='cpm_trans_id',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='datePaiement',
            new_name='cpm_trans_status',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='methodePaiment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='Devise',
            new_name='cel_phone_num',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='EtatTransaction',
            new_name='cpm_amount',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='IdPaiment',
            new_name='cpm_currency',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='IdTransaction',
            new_name='cpm_payid',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='Montant',
            new_name='cpm_payment_date',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='SiteId',
            new_name='cpm_site_id',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='Telephone',
            new_name='cpm_trans_id',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='datePaiement',
            new_name='cpm_trans_status',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trxcorrespondent',
            old_name='methodePaiment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='Devise',
            new_name='cel_phone_num',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='EtatTransaction',
            new_name='cpm_amount',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='IdPaiment',
            new_name='cpm_currency',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='IdTransaction',
            new_name='cpm_payid',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='Montant',
            new_name='cpm_payment_date',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='SiteId',
            new_name='cpm_site_id',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='Telephone',
            new_name='cpm_trans_id',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='datePaiement',
            new_name='cpm_trans_status',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trxfailedcinetpay',
            old_name='methodePaiment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='IdTransactionCorrespondent',
            new_name='cel_phone_numCorrespondant',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='TelephoneCorrespondant',
            new_name='cpm_amount',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='creationCorrespondent',
            new_name='cpm_payment_date',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='datePaiement',
            new_name='cpm_trans_idCorrespondent',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='methodePaimentCorrespondant',
            new_name='created_atCorrespondent',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='montant',
            new_name='payment_methodCorrespondant',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='Devise',
            new_name='cpm_amount',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='EtatTransaction',
            new_name='cpm_currency',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='IdPaiment',
            new_name='cpm_payid',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='IdTransaction',
            new_name='cpm_payment_date',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='Montant',
            new_name='cpm_site_id',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='SiteId',
            new_name='cpm_trans_id',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='datePaiement',
            new_name='cpm_trans_status',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='creation',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='methodePaiment',
            new_name='payment_method',
        ),
        migrations.CreateModel(
            name='Trxreconciled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpm_payment_date', models.CharField(max_length=200)),
                ('idpaiment', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('montant', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('created_atCorrespondent', models.CharField(max_length=200)),
                ('cel_phone_numCorrespondant', models.CharField(max_length=200)),
                ('AmountCorrespodent', models.CharField(max_length=200)),
                ('payment_methodCorrespondant', models.CharField(max_length=200)),
                ('StautTransactionCorrespondent', models.CharField(max_length=200)),
                ('cpm_trans_idCorrespondent', models.CharField(max_length=200)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
