# Generated by Django 3.2.4 on 2021-06-15 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fonction',
            field=models.CharField(default=datetime.datetime(2021, 6, 15, 14, 5, 32, 150747, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='matricule',
            field=models.CharField(default=datetime.datetime(2021, 6, 15, 14, 5, 37, 950436, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
