# Generated by Django 3.2.4 on 2021-06-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20210615_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nom',
            new_name='user',
        ),
    ]
