# Generated by Django 3.2 on 2021-05-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20210522_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='cpm_payid',
            new_name='cpm_payidd',
        ),
    ]
