# Generated by Django 3.2 on 2021-05-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_rename_cpm_payid_trxcinetpay_cpm_payidd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxcinetpay',
            old_name='cpm_payidd',
            new_name='cpm_payid',
        ),
    ]
