# Generated by Django 3.2.4 on 2021-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_rename_nom_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prenom',
        ),
    ]
