# Generated by Django 3.2 on 2021-05-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_rename_cpm_payidd_trxcinetpay_cpm_payid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxsuccesscinetpay',
            old_name='Telephone',
            new_name='cel_phone_num',
        ),
    ]
