# Generated by Django 3.2 on 2021-05-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_rename_telephone_trxsuccesscinetpay_cel_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='cpm_amount',
            new_name='datepaiment',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='cpm_payment_date',
            new_name='montant',
        ),
    ]
