# Generated by Django 3.2.4 on 2021-06-18 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='fileName',
            field=models.CharField(default=datetime.datetime(2021, 6, 18, 18, 19, 53, 218047, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
