# Generated by Django 3.2.4 on 2021-06-21 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_tache_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['-dateCreation']},
        ),
        migrations.AddField(
            model_name='tache',
            name='countCinetpay',
            field=models.CharField(default=datetime.datetime(2021, 6, 21, 18, 23, 35, 395693, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='countOperator',
            field=models.CharField(default=datetime.datetime(2021, 6, 21, 18, 23, 38, 701840, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='diffCount',
            field=models.CharField(default=datetime.datetime(2021, 6, 21, 18, 23, 42, 231044, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='diffMontant',
            field=models.CharField(default=datetime.datetime(2021, 6, 21, 18, 23, 46, 642853, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='montantCinetpay',
            field=models.CharField(default=datetime.datetime(2021, 6, 21, 18, 23, 50, 585834, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='montantOperateur',
            field=models.CharField(default=datetime.datetime(2021, 6, 21, 18, 23, 53, 261378, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tache',
            name='etat',
            field=models.CharField(choices=[('CREATION', 'CREATION'), ('ENCOURS', 'EN COURS'), ('ATTENTE', 'EN ATTENTE DE VALIDATION'), ('VALIDEE', 'TACHE VALIDEE'), ('TERMINEE', 'TACHE TERMINEE')], default='CREATION', max_length=50),
        ),
    ]
