# Generated by Django 3.2 on 2021-05-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0007_auto_20210523_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxdifference',
            old_name='idpaiment',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='trxdifference',
            old_name='idtransaction',
            new_name='payid',
        ),
        migrations.RenameField(
            model_name='trxdifference',
            old_name='datepaiment',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='trxdifference',
            old_name='montant',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='trxdifference',
            old_name='telephone',
            new_name='trans_id',
        ),
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='idpaiment',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='idtransaction',
            new_name='payid',
        ),
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='datepaiment',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='montant',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='telephone',
            new_name='trans_id',
        ),
        migrations.RenameField(
            model_name='trxreconciled',
            old_name='idpaiment',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='trxreconciled',
            old_name='montant',
            new_name='payid',
        ),
        migrations.RenameField(
            model_name='trxreconciled',
            old_name='telephone',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='datepaiment',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='idpaiment',
            new_name='payid',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='montant',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='trxrightcorrespodent',
            old_name='telephone',
            new_name='phone_num',
        ),
    ]
