# Generated by Django 3.2.4 on 2021-06-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0008_auto_20210621_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='countCinetpayAfter',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tache',
            name='countOperatorAfter',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tache',
            name='diffCountAfter',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tache',
            name='diffMontantAfter',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tache',
            name='montantCinetpayAfter',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tache',
            name='montantOperateurAfter',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='countCinetpay',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='countOperator',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='diffCount',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='diffMontant',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='montantCinetpay',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='montantOperateur',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
