# Generated by Django 3.2 on 2021-05-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0008_auto_20210523_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxcorrespondent',
            name='account',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxdifference',
            name='account',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxfailedcinetpay',
            name='account',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxoperateur',
            name='account',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxrightcorrespodent',
            name='account',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxsuccesscinetpay',
            name='account',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
