# Generated by Django 3.2.4 on 2021-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_auto_20210623_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='TrxNonereconciled',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='tache',
            name='TrxReconciled',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='dateDebut',
            field=models.DateTimeField(default='', verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='dateFin',
            field=models.DateTimeField(default='', verbose_name='Date de fin'),
        ),
    ]
