# Generated by Django 3.2 on 2021-05-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0009_auto_20210523_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxreconciled',
            name='Agent',
        ),
        migrations.AddField(
            model_name='trxcorrespondent',
            name='agent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxdifference',
            name='agent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxfailedcinetpay',
            name='agent',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxoperateur',
            name='agent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxreconciled',
            name='agent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxrightcorrespodent',
            name='agent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxsuccesscinetpay',
            name='agent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
