# Generated by Django 3.2.4 on 2021-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0010_auto_20210629_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='dateFinCollect',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='dateFinValidation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='dateValidation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
