# Generated by Django 3.2 on 2021-05-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0011_auto_20210524_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrxNonereconciled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.CharField(max_length=200)),
                ('payid', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('agent', models.CharField(max_length=200)),
                ('created_atCorrespondent', models.CharField(max_length=200)),
                ('cel_phone_numCorrespondant', models.CharField(max_length=200)),
                ('AmountCorrespodent', models.CharField(max_length=200)),
                ('payment_methodCorrespondant', models.CharField(max_length=200)),
                ('StautTransactionCorrespondent', models.CharField(max_length=200)),
                ('cpm_trans_idCorrespondent', models.CharField(max_length=200)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
