# Generated by Django 3.2.4 on 2021-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0012_alter_tache_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
