# Generated by Django 3.2 on 2021-05-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0014_trxnonereconciled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxnonereconciled',
            name='Time',
        ),
    ]
