# Generated by Django 3.2 on 2021-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0015_remove_trxnonereconciled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxnonereconciled',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default=-1.0),
            preserve_default=False,
        ),
    ]
