# Generated by Django 3.2 on 2021-05-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0017_remove_trxnonereconciled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxnonereconciled',
            name='AmountCorrespodent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='StautTransactionCorrespondent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default='2021-02-10 05:01:25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='cel_phone_numCorrespondant',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='cpm_trans_idCorrespondent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='created_atCorrespondent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='payment_methodCorrespondant',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
