# Generated by Django 3.2 on 2021-05-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0019_auto_20210524_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxnonereconciled',
            name='Time',
        ),
    ]
