# Generated by Django 3.2 on 2021-05-24 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0022_auto_20210524_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxnonereconciled',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxreconciled',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 24, 9, 31, 12, 373718, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
