# Generated by Django 3.2 on 2021-05-24 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0023_auto_20210524_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxnonereconciled',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 35, 9, 877365, tzinfo=utc), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='trxreconciled',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 9, 35, 9, 877365, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
