# Generated by Django 3.2 on 2021-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0024_auto_20210524_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxnonereconciled',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trxreconciled',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
