# Generated by Django 3.2 on 2021-05-24 09:38

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0025_auto_20210524_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxnonereconciled',
            name='AmountCorrespodent',
            field=models.CharField(default=datetime.datetime(2021, 5, 24, 9, 37, 39, 27269, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='StautTransactionCorrespondent',
            field=models.CharField(default=datetime.datetime(2021, 5, 24, 9, 37, 45, 459267, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='cel_phone_numCorrespondant',
            field=models.CharField(default=datetime.datetime(2021, 5, 24, 9, 37, 49, 849491, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='cpm_trans_idCorrespondent',
            field=models.CharField(default=datetime.datetime(2021, 5, 24, 9, 37, 53, 77038, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='created_atCorrespondent',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='payment_methodCorrespondant',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
