# Generated by Django 3.2 on 2021-05-31 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0027_auto_20210524_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxcinetpay',
            name='cpm_custom',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 14, 54, 43, 371206, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxcorrespondent',
            name='cpm_custom',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 14, 54, 46, 589208, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxfailedcinetpay',
            name='cpm_custom',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 14, 54, 50, 791400, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='cpm_custom',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 14, 54, 53, 937550, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxreconciled',
            name='cpm_custom',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 14, 54, 59, 373817, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trxsuccesscinetpay',
            name='cpm_custom',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 14, 55, 2, 216894, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
