# Generated by Django 3.2 on 2021-06-07 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0030_auto_20210607_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('etat', models.CharField(choices=[('CREATION', 'CREATION'), ('EXECUTE', 'EXECUTE'), ('ENCOURS', 'EN COURS'), ('RECONCILIATION', 'RECONCILIATION'), ('TERMINE', 'TERMINE')], default='CREATION', max_length=50)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.operateur')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
