# Generated by Django 3.2 on 2021-06-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0031_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxoperateur',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='dateDebut',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='dateFin',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
    ]
