# Generated by Django 3.2 on 2021-06-08 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0032_auto_20210607_2016'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tache',
        #     name='operateur',
        # ),
        # migrations.AddField(
        #     model_name='tache',
        #     name='Operateur',
        #     field=models.CharField(default=datetime.datetime(2021, 6, 8, 8, 59, 43, 456923, tzinfo=utc), max_length=10),
        #     preserve_default=False,
        # ),
    ]
