# Generated by Django 3.2 on 2021-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0033_auto_20210608_1059'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='tache',
        #     name='Operateur',
        #     field=models.CharField(max_length=50),
        # ),
    ]
