# Generated by Django 3.2 on 2021-06-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0034_alter_tache_operateur'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='tache',
        #     old_name='Operateur',
        #     new_name='operateur',
        # ),
    ]
