# Generated by Django 3.2 on 2021-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0035_rename_operateur_tache_operateur'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='tache',
        #     name='operateur',
        #     field=models.CharField(max_length=100),
        # ),
    ]
