# Generated by Django 3.2 on 2021-06-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0037_alter_tache_operateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='dateCreation',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='dateDebut',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='dateFin',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='dateUpdate',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='owner',
        ),
    ]
