# Generated by Django 3.2 on 2021-06-08 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_test', '0038_auto_20210608_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 8, 9, 9, 58, 952163, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='dateDebut',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 9, 10, 35, 162467, tzinfo=utc), verbose_name='Date de début'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='dateFin',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 9, 10, 39, 260555, tzinfo=utc), verbose_name='Date de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='etat',
            field=models.CharField(choices=[('CREATION', 'CREATION'), ('EXECUTE', 'EXECUTE'), ('ENCOURS', 'EN COURS'), ('RECONCILIATION', 'RECONCILIATION'), ('TERMINE', 'TERMINE')], default='CREATION', max_length=50),
        ),
        migrations.AddField(
            model_name='tache',
            name='operateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.operateur'),
        ),
        migrations.AddField(
            model_name='tache',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
