# Generated by Django 3.2 on 2021-06-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0040_auto_20210608_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operateur',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='trxcinetpay',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxcinetpay',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxcorrespondent',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxcorrespondent',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxddvavisa',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxdifference',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxdifference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxdifferenceddvavisa',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxfailedcinetpay',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxfailedcinetpay',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxnonereconciled',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxnonereconciled',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxnonereconciledddvavisa',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxoperateur',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxoperateur',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxreconciled',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxreconciled',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxreconciledddvavisa',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxrightcorrespodent',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxrightcorrespodent',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxrightcorrespodentddvavisa',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trxsuccesscinetpay',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='trxsuccesscinetpay',
            name='owner',
        ),
        migrations.AddField(
            model_name='trxcorrespondent',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxddvavisa',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxdifference',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxdifferenceddvavisa',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxfailedcinetpay',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxnonereconciled',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxnonereconciledddvavisa',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxreconciled',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxreconciledddvavisa',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxrightcorrespodent',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxrightcorrespodentddvavisa',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AddField(
            model_name='trxsuccesscinetpay',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_test.tache'),
        ),
        migrations.AlterField(
            model_name='operateur',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
