# Generated by Django 3.2 on 2021-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0041_auto_20210608_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='etat',
            field=models.CharField(choices=[('CREATION', 'CREATION'), ('ENCOURS', 'EN COURS'), ('TERMINEE', 'TERMINEE'), ('VALIDEE', 'VALIDEE')], default='CREATION', max_length=50),
        ),
    ]
