# Generated by Django 3.2 on 2021-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrxOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('reference', models.CharField(max_length=200)),
                ('operation', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('CompteOM', models.CharField(max_length=200)),
                ('correspondant', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200)),
            ],
        ),
    ]
