# Generated by Django 3.2 on 2021-05-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0002_trxcinetpay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='reference',
            new_name='IdPaiment',
        ),
    ]
