# Generated by Django 3.2 on 2021-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0004_correspondant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correspondant',
        ),
        migrations.AlterField(
            model_name='trxcinetpay',
            name='creation',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxoperateur',
            name='date',
            field=models.DateTimeField(max_length=200),
        ),
    ]
