# Generated by Django 3.2 on 2021-05-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0006_auto_20210505_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='IdPaiment',
            new_name='idpaiment',
        ),
        migrations.RenameField(
            model_name='trxoperateur',
            old_name='operation',
            new_name='idtransaction',
        ),
    ]
