# Generated by Django 3.2 on 2021-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0007_auto_20210505_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrxDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepaiment', models.DateTimeField(max_length=200)),
                ('idpaiment', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('montant', models.CharField(max_length=200)),
                ('idtransaction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrxFailedCinetpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(max_length=200)),
                ('datePaiement', models.CharField(max_length=200)),
                ('marchand', models.CharField(max_length=200)),
                ('EmailMarchand', models.CharField(max_length=200)),
                ('NomDuService', models.CharField(max_length=200)),
                ('IdTransaction', models.CharField(max_length=200)),
                ('SiteId', models.CharField(max_length=200)),
                ('Montant', models.CharField(max_length=200)),
                ('Devise', models.CharField(max_length=200)),
                ('methodePaiment', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('EtatTransaction', models.CharField(max_length=200)),
                ('IdPaiment', models.CharField(max_length=200)),
            ],
        ),
    ]
