# Generated by Django 3.2 on 2021-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0011_trxsuccesscinetpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxrightcorrespodent',
            name='IdTransactionCorrespondent',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
