# Generated by Django 3.2 on 2021-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0012_trxrightcorrespodent_idtransactioncorrespondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxcinetpay',
            name='creation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxcorrespondent',
            name='creation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxdifference',
            name='datepaiment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxfailedcinetpay',
            name='creation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxsuccesscinetpay',
            name='creation',
            field=models.CharField(max_length=200),
        ),
    ]
