# Generated by Django 3.2 on 2021-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0013_auto_20210510_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxcinetpay',
            name='creation',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxcorrespondent',
            name='creation',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxdifference',
            name='datepaiment',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxfailedcinetpay',
            name='creation',
            field=models.DateTimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trxsuccesscinetpay',
            name='creation',
            field=models.DateTimeField(max_length=200),
        ),
    ]
