# Generated by Django 3.2 on 2021-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0014_auto_20210510_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxrightcorrespodent',
            name='idpaiment',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
