# Generated by Django 3.2 on 2021-05-31 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0018_auto_20210531_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trxcinetpay',
            name='cpm_custom',
        ),
        migrations.RemoveField(
            model_name='trxcorrespondent',
            name='cpm_custom',
        ),
        migrations.RemoveField(
            model_name='trxfailedcinetpay',
            name='cpm_custom',
        ),
        migrations.RemoveField(
            model_name='trxrightcorrespodent',
            name='cpm_custom',
        ),
        migrations.RemoveField(
            model_name='trxsuccesscinetpay',
            name='cpm_custom',
        ),
    ]
